### ISSUE TITLE
Cannot find module 'jsonwebtoken'

### ISSUE THREAD

**Issue by goeldicom** [strukturag/pdfdraw#15]
After installing all dependencies as described, I get this at service start in syslog:

```
Jan 25 13:34:20 cloud systemd[1]: Started PDF Annotation service for Nextcloud.
Jan 25 13:34:20 cloud nodejs[16951]: internal/modules/cjs/loader.js:638
Jan 25 13:34:20 cloud nodejs[16951]:     throw err;
Jan 25 13:34:20 cloud nodejs[16951]:     ^
Jan 25 13:34:20 cloud nodejs[16951]: Error: Cannot find module 'jsonwebtoken'
Jan 25 13:34:20 cloud nodejs[16951]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Jan 25 13:34:20 cloud nodejs[16951]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Jan 25 13:34:20 cloud nodejs[16951]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Jan 25 13:34:20 cloud nodejs[16951]:     at require (internal/modules/cjs/helpers.js:25:18)
Jan 25 13:34:20 cloud nodejs[16951]:     at Object.<anonymous> (/var/www/nextcloud/apps/pdfdraw/server/server.js:46:11)
Jan 25 13:34:20 cloud nodejs[16951]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Jan 25 13:34:20 cloud nodejs[16951]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Jan 25 13:34:20 cloud nodejs[16951]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jan 25 13:34:20 cloud nodejs[16951]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jan 25 13:34:20 cloud nodejs[16951]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jan 25 13:34:20 cloud systemd[1]: pdfdraw.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 13:34:20 cloud systemd[1]: pdfdraw.service: Failed with result 'exit-code'.
```

This is on a Ubuntu 20.04 server.

**Comment by cig0** [comment]
@goeldicom Have you tried building an imaging and serving the server from a container?

**Comment by rekXx** [comment]
ssh into your server. Go to the server folder of pdfdraw and run
`npm install jsonwebtoken`

**Comment by szaimen** [comment]
related https://github.com/strukturag/pdfdraw/issues/23

**Comment by fancycode** [comment]
Should be fixed with #26 that adds the `package.json` back to the appstore tarball.

**Comment by szaimen** [comment]
> Should be fixed with #26 that adds the package.json back to the appstore tarball.

At least after a new release gets published to the appstore ;)

**Comment by szaimen** [comment]
@fancycode code you maybe create a new release? 
Would be great so that I can finish https://github.com/nextcloud/vm/pull/1870 :)
(doesn't need to be a NC21 compatible release)

**Comment by szaimen** [comment]
ping @fancycode
Please make a new release or is something missing for that?
