### ISSUE TITLE
[webpack-cli] HookWebpackError: Not supported

### ISSUE THREAD

**Issue by tiandiyiqi** [strukturag/pdfdraw#73]
`make
npm install
npm WARN pdfjs-dist@2.9.359 requires a peer of worker-loader@^3.0.7 but none is installed. You must install peer dependencies yourself.

audited 366 packages in 2.198s

51 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm run build

> pdfdraw@0.1.0 build /var/www/html/seacloud/apps/pdfdraw
> NODE_ENV=production webpack --progress --config webpack.js

[webpack-cli] **HookWebpackError: Not supported**
    at makeWebpackError (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at hooks.processAssets.callAsync.err (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:3055:12)
    at eval (eval at create (/var/www/html/seacloud/apps/pdfdraw/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:51:1)
    at err (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:508:26)
    at compilation.hooks.processAssets.tapAsync (/var/www/html/seacloud/apps/pdfdraw/node_modules/copy-webpack-plugin/dist/index.js:485:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-- inner error --
Error: Not supported
    at compilation.hooks.processAssets.tapAsync (/var/www/html/seacloud/apps/pdfdraw/node_modules/copy-webpack-plugin/dist/index.js:481:13)
    at fn (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:507:9)
    at Hook.eval [as callAsync] (eval at create (/var/www/html/seacloud/apps/pdfdraw/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:48:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/html/seacloud/apps/pdfdraw/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:3052:34)
    at createChunkAssets.err (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:3100:10)
    at symbolIterator (/var/www/html/seacloud/apps/pdfdraw/node_modules/neo-async/async.js:3485:9)
    at timesSync (/var/www/html/seacloud/apps/pdfdraw/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/var/www/html/seacloud/apps/pdfdraw/node_modules/neo-async/async.js:3463:5)
    at Compilation.createChunkAssets (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:4452:12)
caused by plugins in Compilation.hooks.processAssets
Error: Not supported
    at compilation.hooks.processAssets.tapAsync (/var/www/html/seacloud/apps/pdfdraw/node_modules/copy-webpack-plugin/dist/index.js:481:13)
    at fn (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:507:9)
    at Hook.eval [as callAsync] (eval at create (/var/www/html/seacloud/apps/pdfdraw/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:48:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/html/seacloud/apps/pdfdraw/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:3052:34)
    at createChunkAssets.err (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:3100:10)
    at symbolIterator (/var/www/html/seacloud/apps/pdfdraw/node_modules/neo-async/async.js:3485:9)
    at timesSync (/var/www/html/seacloud/apps/pdfdraw/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/var/www/html/seacloud/apps/pdfdraw/node_modules/neo-async/async.js:3463:5)
    at Compilation.createChunkAssets (/var/www/html/seacloud/apps/pdfdraw/node_modules/webpack/lib/Compilation.js:4452:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pdfdraw@0.1.0 build: `NODE_ENV=production webpack --progress --config webpack.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the pdfdraw@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-10T12_46_34_068Z-debug.log
make: *** [Makefile:48：build] error 2
`

**Comment by tiandiyiqi** [comment]
change the packedge.json
"copy-webpack-plugin": "10.0.0",--->"copy-webpack-plugin": "9.*",

**Comment by fancycode** [comment]
Which version of node.js is this? Minimum supported version for the copy-webpack-plugin 10 is Node 12, so you might need to update your build environment.
